<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>OnlineResumeMaker</title>
  <link rel="stylesheet" href="./main.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="./assets/js/jquery-3.4.1.min.js"></script>
  <script src="./assets/js/load.js"></script>
</head>

<body>
  <div id="container">
    <!-- header -->
    <header>
      <div class="container">
        <div class="row">
          <div class="left-col">
            <a href="index.jsp"><img src="./ormlogo.png" alt="logo" class="logo"></a>
          </div>
         <div class="right-col">
          <% 
if(session.getAttribute("name")!=null){
	%>
	<ul>
            <li><a href="index.jsp">Home</a></li>
              <li><a href="#">Resume Templates</a></li>
              <li><a href="#">Resume Builder</a></li>
              <li><span class="wel"><img
                    src="https://cdn.resumebuild.com/assets/icon-user-79ac7564fb55c510a0712b870cbd33c11cc7f30d0045904c7117c38b10c7ac70.svg"
                    alt="img"> <%=session.getAttribute("name")%></span></li>
                <li><a href="logout"><i class="fa fa-sign-out"></i></a></li>
                    
            </ul>
	<%
}else{
	%>
	<ul>
            <li><a href="index.jsp">Home</a></li>
              <li><a href="#">Resume Templates</a></li>
              <li><a href="#">Resume Builder</a></li>
              <li>
                <button class="signin"><img
                    src="https://cdn.resumebuild.com/assets/icon-user-79ac7564fb55c510a0712b870cbd33c11cc7f30d0045904c7117c38b10c7ac70.svg"
                    alt="img"> Sign In</button></li>
            </ul>
	<%
}
%>
          </div>
        </div>
      </div>
    </header>
    <!-- feature -->
    <div class="featureall">
      <div class="feature">
        <div class="container">
          <div class="row">
            <div class="left-col">
              <div class="left-col-desc">
                <h1>IMPRESSIVE RESUMES</h1><span>EASY ONLINE BUILDER</span>
                <p><i class="fa fa-check"></i> Professional out-of-the-box resumes, instantly generated by the most
                  advanced resume builder technology
                  available.</p>
                <p><i class="fa fa-check"></i> Effortless crafting. Real-time preview & pre-written resume examples.
                  Dozens of HR-approved resume templates.</p>
                <p><i class="fa fa-check"></i> Land your dream job with the perfect resume employers are looking for!
                </p>
                
                <% 
if(session.getAttribute("name")==null){
	%>
	 <button class="bmr">Build My Resume</button>
	<%
}else{
	%>
 <button class="bmrr">Build My Resume</button>
	<%
}
%>
               
              </div>
            </div>
            <div class="right-col">
              <img src="./intro.png" alt="img">
            </div>
          </div>
        </div>
      </div>
      <!-- feature2 -->
      <div class="feature2">
        <div class="feature-col">

        </div>
        <div class="overflow">
          <div class="container">
            <h2>3 EASY STEPS TO CREATE YOUR PERFECT RESUME</h2>
            <div class="row">
              <div class="left-col">
                <div class="circle">
                  <img
                    src="https://cdn.resumebuild.com/assets/icon-cv-fb4b6b2810d55d5480c5275bf38f67f1820eea55e82b07347b09963c5ec9efe7.svg"
                    alt="img">
                </div>
                <h3>Choose your<br>resume template</h3>
                <p>Our professional resume templates are designed strictly following all industry guidelines and best
                  practices<br> employers are looking for.</p>
              </div>
              <div class="middle-col">
                <div class="circle">
                  <img
                    src="https://cdn.resumebuild.com/assets/icon-pen-3c10fefc5c8094adab81f509baa0625208887d1557c66dfe678d586cd8b8c09f.svg"
                    alt="img">
                </div>
                <h3>Show what <br>you´re made of</h3>
                <p>Not finding the right words to showcase yourself? We´ve added thousands of pre-written examples and
                  resume samples. <br>As easy as a click.</p>
              </div>
              <div class="right-col">
                <div class="circle">
                  <img
                    src="https://cdn.resumebuild.com/assets/icon-download2-9f518b607f810b4239b34a2d4f92ce038dfe7f112a8729137cd3eea3bac37530.svg"
                    alt="img">
                </div>
                <h3>Download <br> Your resume</h3>
                <p>Start impressing employers. Download your awesome resume and land the job you are looking for,
                  effortlessly. </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="left-col">
            <img src="./ormlogo.png" alt="logo" class="logo">
          </div>
          <div class="right-col">
            <p>Copyright © 2019. All rights reserved.</p>
          </div>
        </div>
      </div>
    </footer>
  </div>
</body>

</html>